// src/components/ablsoftware/Maintance/common/BiltiesReceivablePdf.ts

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const COMPANY_NAME = "AL NASAR BASHEER LOGISTICS";
const REPORT_TITLE = "Bilties Receivable";

export interface BiltiesReceivableRow {
  serial?: number | string;
  orderNo: string;
  orderDate?: string;
  vehicleNo?: string;
  biltyNo?: string;
  biltyDate?: string;
  consignor?: string;
  consignee?: string;
  carrier?: string;
  vendor?: string;
  departure?: string;
  destination?: string;
  vehicleType?: string;
  article?: string;
  qty?: string;
  biltyAmount?: number;
  receivedAmount?: number;
  pendingAmount?: number;
  ablDate?: string;
}

export interface BiltiesReceivablePdfParams {
  rows: BiltiesReceivableRow[];
  startDate?: string;
  endDate?: string;
  exportType?: 'bilty' | 'party';
  partyType?: 'consignor' | 'consignee' | 'all';
}

const formatDisplayDate = (d?: string) => {
  if (!d) return "-";
  try {
    const dt = new Date(d);
    if (Number.isNaN(dt.getTime())) return d;
    const dd = String(dt.getDate()).padStart(2, "0");
    const mm = String(dt.getMonth() + 1).padStart(2, "0");
    const yyyy = dt.getFullYear();
    return `${dd}-${mm}-${yyyy}`;
  } catch {
    return d;
  }
};

const numberOr0 = (v: any) => {
  const n = typeof v === "string" ? parseFloat(v) : v;
  return isNaN(n) || !isFinite(n) ? 0 : n;
};

const formatCurrency = (num: any) =>
  numberOr0(num).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

export const exportBiltiesReceivableToPDF = ({
  rows,
  startDate,
  endDate,
  exportType = "bilty",
  partyType = "consignor",
}: BiltiesReceivablePdfParams) => {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "A4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  let headerShown = false;

  const addCompanyHeader = () => {
    doc.setFillColor(41, 128, 185);
    doc.rect(0, 0, pageWidth, 55, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(19);
    doc.setTextColor(255, 255, 255);
    doc.text(COMPANY_NAME, pageWidth / 2, 32, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(240, 240, 240);
    doc.text("Transport & Logistics Solutions", pageWidth / 2, 48, { align: "center" });
  };

  const addReportTitleAndDate = () => {
      const partyLabel = partyType === "consignor" ? "Consignor" : (partyType === 'consignee' ? 'Consignee' : 'Consignor / Consignee');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    const title =
      exportType === "party"
        ? `Party Wise Receivable Report (${partyLabel})`
        : `Bilty Wise Receivable Report (${partyLabel})`;
    doc.text(title, pageWidth / 2, 80, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);

    doc.text(
      `From: ${startDate ? formatDisplayDate(startDate) : "All Dates"}`,
      40,
      100,
      { align: "left" }
    );
    doc.text(
      `To: ${endDate ? formatDisplayDate(endDate) : "All Dates"}`,
      pageWidth / 2,
      100,
      { align: "center" }
    );
    doc.text(
      `Generated: ${formatDisplayDate(new Date().toISOString())} at ${new Date().toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      })}`,
      pageWidth - 40,
      100,
      { align: "right" }
    );

    doc.setDrawColor(41, 128, 185);
    doc.setLineWidth(1.2);
    doc.line(40, 110, pageWidth - 40, 110);
  };

  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(
      `Generated by ZMS - Al Nasar Basheer Logistics Management System`,
      40,
      doc.internal.pageSize.height - 18
    );
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth - 40,
      doc.internal.pageSize.height - 18,
      { align: "right" }
    );
  };

  // ────────────────────────────────────────────────
  //  BILTY WISE – Flat table
  // ────────────────────────────────────────────────
  if (exportType === "bilty") {
    addCompanyHeader();
    addReportTitleAndDate();

    const head = [
      partyType === 'all'
        ? [
            "Vehicle No",
            "Bilty No",
            "Bilty Date",
            "Consignor",
            "Consignee",
            "Item Description",
            "Quantity",
            "Bilty Amount (PKR)",
            "Received (PKR)",
            "Pending (PKR)",
          ]
        : [
            "Vehicle No",
            "Bilty No",
            "Bilty Date",
            partyType === "consignor" ? "Consignor" : "Consignee",
            "Item Description",
            "Quantity",
            "Bilty Amount (PKR)",
            "Received (PKR)",
            "Pending (PKR)",
          ],
    ];

    const body = rows.map((r) => 
      partyType === 'all'
        ? [
            r.vehicleNo || "-",
            r.biltyNo || "-",
            formatDisplayDate(r.biltyDate || r.orderDate),
            r.consignor || "-",
            r.consignee || "-",
            r.article || "-",
            r.qty || "-",
            formatCurrency(r.biltyAmount),
            formatCurrency(r.receivedAmount),
            formatCurrency(r.pendingAmount),
          ]
        : [
            r.vehicleNo || "-",
            r.biltyNo || "-",
            formatDisplayDate(r.biltyDate || r.orderDate),
            (partyType === "consignor" ? r.consignor : r.consignee) || "-",
            r.article || "-",
            r.qty || "-",
            formatCurrency(r.biltyAmount),
            formatCurrency(r.receivedAmount),
            formatCurrency(r.pendingAmount),
          ]
    );

    // Grand total
    const grandTotal = rows.reduce(
      (acc, r) => ({
        bilty: acc.bilty + numberOr0(r.biltyAmount),
        received: acc.received + numberOr0(r.receivedAmount),
        pending: acc.pending + numberOr0(r.pendingAmount),
      }),
      { bilty: 0, received: 0, pending: 0 }
    );

    body.push(
      partyType === 'all'
        ? [
            { content: "GRAND TOTAL", colSpan: 5, styles: { halign: "right", fontStyle: "bold" } },
            { content: formatCurrency(grandTotal.bilty), styles: { fontStyle: "bold" } },
            { content: formatCurrency(grandTotal.received), styles: { fontStyle: "bold" } },
            { content: formatCurrency(grandTotal.pending), styles: { fontStyle: "bold", textColor: [220, 53, 69] } },
          ]
        : [
            { content: "GRAND TOTAL", colSpan: 4, styles: { halign: "right", fontStyle: "bold" } },
            { content: formatCurrency(grandTotal.bilty), styles: { fontStyle: "bold" } },
            { content: formatCurrency(grandTotal.received), styles: { fontStyle: "bold" } },
            { content: formatCurrency(grandTotal.pending), styles: { fontStyle: "bold", textColor: [220, 53, 69] } },
          ]
    );

    autoTable(doc, {
      startY: 125,
      head,
      body,
      theme: "grid",
      styles: { fontSize: 8, cellPadding: 5, lineWidth: 0.4, lineColor: [180, 180, 180] },
      headStyles: {
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        halign: "center",
      },
      columnStyles: partyType === 'all' ? {
        0: { cellWidth: 70 },
        1: { cellWidth: 70 },
        2: { cellWidth: 70 },
        3: { cellWidth: 100 },
        4: { cellWidth: 100 },
        5: { cellWidth: 130 },
        6: { cellWidth: 70 },
        7: { halign: "right", cellWidth: 75 },
        8: { halign: "right", cellWidth: 70 },
        9: { halign: "right", cellWidth: 70, textColor: [220, 53, 69] },
      } : {
        0: { cellWidth: 70 },
        1: { cellWidth: 70 },
        2: { cellWidth: 70 },
        3: { cellWidth: 140 },
        4: { cellWidth: 140 },
        5: { cellWidth: 70 },
        6: { halign: "right", cellWidth: 80 },
        7: { halign: "right", cellWidth: 70 },
        8: { halign: "right", cellWidth: 70, textColor: [220, 53, 69] },
      },
      margin: { left: 40, right: 40 },
      didDrawPage: () => {
        if (!headerShown) {
          headerShown = true;
        }
      },
      willDrawPage: (data) => {
        if (data.pageNumber > 1 && !headerShown) {
          addCompanyHeader();
          addReportTitleAndDate();
        }
      },
    });

    const finalY = (doc as any).lastAutoTable.finalY;
    addFooter(1, 1); // will be updated later if needed
  }

  // ────────────────────────────────────────────────
  //  PARTY WISE – Grouped + subtotals
  // ────────────────────────────────────────────────
  else {
    const grouped: Record<string, BiltiesReceivableRow[]> = {};

    if (partyType === 'all') {
      // When 'all' requested, build two sets: consignor groups then consignee groups, both sorted alphabetically
      const consignorGrouped: Record<string, BiltiesReceivableRow[]> = {};
      const consigneeGrouped: Record<string, BiltiesReceivableRow[]> = {};
      rows.forEach((r) => {
        const cKey = r.consignor && r.consignor.trim() ? r.consignor.trim() : 'Unknown Party';
        const eKey = r.consignee && r.consignee.trim() ? r.consignee.trim() : 'Unknown Party';
        if (!consignorGrouped[cKey]) consignorGrouped[cKey] = [];
        if (!consigneeGrouped[eKey]) consigneeGrouped[eKey] = [];
        consignorGrouped[cKey].push(r);
        consigneeGrouped[eKey].push(r);
      });
      // merge into grouped with prefix to preserve order (consignor first), sorted alphabetically
      Object.entries(consignorGrouped).sort(([a], [b]) => a.localeCompare(b)).forEach(([k, v]) => (grouped[`Consignor: ${k}`] = v));
      Object.entries(consigneeGrouped).sort(([a], [b]) => a.localeCompare(b)).forEach(([k, v]) => (grouped[`Consignee: ${k}`] = v));
    } else {
      rows.forEach((r) => {
        const partyKey = partyType === "consignor" ? r.consignor : r.consignee;
        const key = partyKey && partyKey.trim() ? partyKey.trim() : "Unknown Party";
        if (!grouped[key]) grouped[key] = [];
        grouped[key].push(r);
      });
    }

    let pageNum = 1;
    let totalPagesEstimate = 1;
    let isFirstPage = true; // Track if it's the first page

    // Add header only on first page
    addCompanyHeader();
    addReportTitleAndDate();

    let currentY = 125;

    Object.entries(grouped).forEach(([partyName, partyRows], groupIndex) => {
      // Page break check
      if (currentY > doc.internal.pageSize.height - 140) {
        addFooter(pageNum, totalPagesEstimate);
        doc.addPage();
        pageNum++;
        isFirstPage = false; // Not first page anymore
        // Don't add company header on new pages
        currentY = 40; // Start from top on new pages
      }

      // Party name header
      doc.setFillColor(230, 243, 255);
      doc.rect(40, currentY - 12, pageWidth - 80, 24, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(41, 128, 185);
      // When partyType is 'all', partyName already contains "Consignor: " or "Consignee: " prefix
      const displayPartyName = partyType === 'all' ? partyName : `${partyType === "consignor" ? "Consignor" : "Consignee"}: ${partyName}`;
      doc.text(displayPartyName, 50, currentY + 3);

      currentY += 28;

      const head = [
        [
          "Vehicle No",
          "Bilty No",
          "Bilty Date",
          "Destination",
          "Item Description",
          "Quantity",
          "Bilty Amount (PKR)",
          "Received (PKR)",
          "Pending (PKR)",
        ],
      ];

      const body = partyRows.map((r) => [
        r.vehicleNo || "-",
        r.biltyNo || "-",
        formatDisplayDate(r.biltyDate || r.orderDate),
        r.destination || "-",
        r.article || "-",
        r.qty || "-",
        formatCurrency(r.biltyAmount),
        formatCurrency(r.receivedAmount),
        formatCurrency(r.pendingAmount),
      ]);

      const subtotal = partyRows.reduce(
        (acc, r) => ({
          bilty: acc.bilty + numberOr0(r.biltyAmount),
          received: acc.received + numberOr0(r.receivedAmount),
          pending: acc.pending + numberOr0(r.pendingAmount),
        }),
        { bilty: 0, received: 0, pending: 0 }
      );

      body.push([
        { content: "SUBTOTAL", colSpan: 6, styles: { halign: "right", fontStyle: "bold" } },
        { content: formatCurrency(subtotal.bilty), styles: { fontStyle: "bold" } },
        { content: formatCurrency(subtotal.received), styles: { fontStyle: "bold" } },
        { content: formatCurrency(subtotal.pending), styles: { fontStyle: "bold", textColor: [220, 53, 69] } },
      ]);

      autoTable(doc, {
        startY: currentY,
        head: head, // Always show header for each party table
        body,
        theme: "grid",
        styles: { fontSize: 8, cellPadding: 5, lineWidth: 0.4, lineColor: [190, 190, 190] },
        headStyles: {
          fillColor: [41, 128, 185],
          textColor: 255,
          fontStyle: "bold",
          halign: "center",
        },
        columnStyles: {
          0: { cellWidth: 80 },
          1: { cellWidth: 80 },
          2: { cellWidth: 70 },
          3: { cellWidth: 90 },
          4: { cellWidth: 140 },
          5: { cellWidth: 80 },
          6: { halign: "right", cellWidth: 80 },
          7: { halign: "right", cellWidth: 70 },
          8: { halign: "right", cellWidth: 70, textColor: [220, 53, 69] },
        },
        margin: { left: 40, right: 40 },
        didParseCell: (data) => {
          if (data.row.index === body.length - 1 && data.column.index >= 6) {
            data.cell.styles.fillColor = [245, 247, 250];
          }
        },
      });

      currentY = (doc as any).lastAutoTable.finalY + 18;
    });

    addFooter(pageNum, pageNum);
  }

  const filename = `Al_Nasar_Basheer_Logistics_Receivable_${exportType === "party" ? "PartyWise" : "BiltyWise"}_${new Date().toISOString().slice(0, 10)}.pdf`;

  doc.save(filename);
};