// src/components/ablsoftware/Maintance/common/BiltiesReceivablePdf.ts

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Company constants (reuse style from BookingOrderPdf)
const COMPANY_NAME = "AL NASAR BASHEER LOGISTICS";
const REPORT_TITLE = "Bilties Receivable";

export interface BiltiesReceivableRow {
  serial?: number | string;
  orderNo: string;
  orderDate?: string;
  vehicleNo?: string;
  biltyNo?: string;
  biltyDate?: string;
  consignor?: string;
  consignee?: string;
  carrier?: string; // transporter
  vendor?: string;
  departure?: string; // fromLocation
  destination?: string; // toLocation
  vehicleType?: string;
  article?: string;
  qty?: string;
  biltyAmount?: number;
  receivedAmount?: number;
  pendingAmount?: number;
  ablDate?: string;
}

export interface BiltiesReceivablePdfParams {
  rows: BiltiesReceivableRow[];
  startDate?: string; // yyyy-mm-dd
  endDate?: string; // yyyy-mm-dd
  dateFilter?: string;
  columns?: string;
  valueFilter?: string;
  sorting?: string;
  quickActions?: string;
  exportType?: 'bilty' | 'party';
  partyType?: 'consignor' | 'consignee'; // New: to determine which party column to use
}

const formatDisplayDate = (d?: string) => {
  if (!d) return "-";
  // Expect yyyy-mm-dd or ISO
  try {
    const dt = new Date(d);
    if (Number.isNaN(dt.getTime())) return d;
    const dd = String(dt.getDate()).padStart(2, "0");
    const mm = String(dt.getMonth() + 1).padStart(2, "0");
    const yyyy = dt.getFullYear();
    return `${dd}-${mm}-${yyyy}`;
  } catch {
    return d;
  }
};

export const exportBiltiesReceivableToPDF = ({ rows, startDate, endDate, dateFilter, columns, valueFilter, sorting, quickActions, exportType = 'bilty', partyType = 'consignor' }: BiltiesReceivablePdfParams) => {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "A4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Add page number function
  const addPageNumber = (pageNum: number, totalPages: number) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 40, pageHeight - 20, { align: "right" });
  };

  // Header styling
  const addHeader = () => {
    // Company name with better styling
    doc.setFillColor(41, 128, 185); // Professional blue
    doc.rect(0, 0, pageWidth, 60, 'F');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text(COMPANY_NAME, pageWidth / 2, 35, { align: "center" });

    // Subtitle
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(240, 240, 240);
    doc.text("Transport & Logistics Solutions", pageWidth / 2, 50, { align: "center" });
  };

  // Footer
  const addFooter = () => {
    doc.setFillColor(240, 240, 240);
    doc.rect(0, pageHeight - 40, pageWidth, 40, 'F');

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by ZMS - Al Nasar Basheer Logistics Management System", 40, pageHeight - 25);
    doc.text(`Report Date: ${formatDisplayDate(new Date().toISOString())}`, 40, pageHeight - 15);
  };

  addHeader();
  addFooter();

  // Title - Updated to show party type
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(41, 128, 185);
  const partyLabel = partyType === 'consignor' ? 'Consignor' : 'Consignee';
  const title = exportType === 'party' ? `Party Wise Receivable Report (${partyLabel})` : `Bilty Wise Receivable Report (${partyLabel})`;
  doc.text(title, pageWidth / 2, 85, { align: "center" });

  // Date information with better styling
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);

  const startText = `From: ${startDate ? formatDisplayDate(startDate) : "All Dates"}`;
  const toText = `To: ${endDate ? formatDisplayDate(endDate) : "All Dates"}`;
  const nowText = `Generated: ${formatDisplayDate(new Date().toISOString())} at ${new Date().toLocaleTimeString()}`;

  doc.text(startText, 40, 105, { align: "left" });
  doc.text(toText, pageWidth / 2, 105, { align: "center" });
  doc.text(nowText, pageWidth - 40, 105, { align: "right" });

  // Separator line
  doc.setDrawColor(41, 128, 185);
  doc.setLineWidth(2);
  doc.line(40, 115, pageWidth - 40, 115);

  let currentY = 135;
  let pageNum = 1;
  const totalPages = 1; // Will be updated if multiple pages

  addPageNumber(pageNum, totalPages);

  const numberOr0 = (v: any) => {
    const n = typeof v === "string" ? parseFloat(v) : v;
    return isNaN(n) || !isFinite(n) ? 0 : n;
  };

  const formatCurrency = (num: any) => {
    return numberOr0(num).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  };

  if (exportType === 'party') {
    // Group by selected party type (Consignor or Consignee)
    const grouped: Record<string, BiltiesReceivableRow[]> = {};
    rows.forEach(r => {
      const party = partyType === 'consignor' ? (r.consignor || "Unknown Party") : (r.consignee || "Unknown Party");
      if (!grouped[party]) grouped[party] = [];
      grouped[party].push(r);
    });

    let headerShownOnPage = false;
    const partyLabel = partyType === 'consignor' ? 'Consignor' : 'Consignee';
    const head = [[
      "Vehicle No",
      "Bilty No",
      "Bilty Date",
      "Destination",
      "Item Description",
      "Quantity",
      "Bilty Amount (PKR)",
      "Received (PKR)",
      "Pending (PKR)"
    ]];

    Object.entries(grouped).forEach(([partyName, partyRows], index) => {
      // Check if we need a new page
      if (currentY + 100 > pageHeight - 60) {
        addFooter();
        addPageNumber(pageNum, totalPages);
        doc.addPage();
        pageNum++;
        addHeader();
        addFooter();
        currentY = 135;
        headerShownOnPage = false;
      }

      // Party name with professional styling
      doc.setFillColor(240, 248, 255); // Light blue background
      doc.rect(40, currentY - 5, pageWidth - 80, 20, 'F');

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(41, 128, 185);
      doc.text(`${partyLabel}: ${partyName}`, 50, currentY + 8);
      currentY += 25;

      const body = partyRows.map(r => [
        r.vehicleNo || "-",
        r.biltyNo || "-",
        formatDisplayDate(r.biltyDate || r.orderDate),
        r.destination || "-",
        r.article || "-",
        r.qty || "-",
        formatCurrency(r.biltyAmount),
        formatCurrency(r.receivedAmount),
        formatCurrency(r.pendingAmount)
      ]);

      // Calculate totals for this party
      const partytotals = partyRows.reduce((acc, r) => {
        acc.bilty += numberOr0(r.biltyAmount);
        acc.received += numberOr0(r.receivedAmount);
        acc.pending += numberOr0(r.pendingAmount);
        return acc;
      }, { bilty: 0, received: 0, pending: 0 });

      body.push([
        { content: "SUBTOTAL", colSpan: 6, styles: { halign: 'right', fontStyle: 'bold', fillColor: [240, 248, 255] } },
        { content: formatCurrency(partytotals.bilty), styles: { fontStyle: 'bold', fillColor: [240, 248, 255] } },
        { content: formatCurrency(partytotals.received), styles: { fontStyle: 'bold', fillColor: [240, 248, 255] } },
        { content: formatCurrency(partytotals.pending), styles: { fontStyle: 'bold', fillColor: [240, 248, 255], textColor: [220, 53, 69] } }
      ]);

      autoTable(doc, {
        startY: currentY,
        head: headerShownOnPage ? [] : head,
        body,
        styles: {
          fontSize: 8,
          cellPadding: 5,
          lineColor: [200, 200, 200],
          lineWidth: 0.5
        },
        headStyles: {
          fillColor: [41, 128, 185],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center'
        },
        bodyStyles: {
          textColor: [50, 50, 50]
        },
        alternateRowStyles: {
          fillColor: [248, 249, 250]
        },
        columnStyles: {
          6: { halign: 'right' },
          7: { halign: 'right' },
          8: { halign: 'right', textColor: [220, 53, 69], fontStyle: 'bold' }
        },
        theme: 'grid',
        margin: { left: 40, right: 40 },
        didDrawPage: () => {
          headerShownOnPage = true;
        }
      });

      currentY = (doc as any).lastAutoTable.finalY + 20;
    });

  } else {
    // Bilty Wise - Show selected party type column
    const partyLabel = partyType === 'consignor' ? 'Consignor' : 'Consignee';
    const head = [[
      "Vehicle No",
      "Bilty No",
      "Bilty Date",
      partyLabel,
      "Item Description",
      "Quantity",
      "Bilty Amount (PKR)",
      "Received (PKR)",
      "Pending (PKR)"
    ]];

    const body = rows.map(r => [
      r.vehicleNo || "-",
      r.biltyNo || "-",
      formatDisplayDate(r.biltyDate || r.orderDate),
      partyType === 'consignor' ? (r.consignor || "-") : (r.consignee || "-"),
      r.article || "-",
      r.qty || "-",
      formatCurrency(r.biltyAmount),
      formatCurrency(r.receivedAmount),
      formatCurrency(r.pendingAmount)
    ]);

    // Calculate totals
    const totals = rows.reduce((acc, r) => {
      acc.bilty += numberOr0(r.biltyAmount);
      acc.received += numberOr0(r.receivedAmount);
      acc.pending += numberOr0(r.pendingAmount);
      return acc;
    }, { bilty: 0, received: 0, pending: 0 });

    body.push([
      { content: "GRAND TOTAL", colSpan: 6, styles: { halign: 'right', fontStyle: 'bold', fillColor: [41, 128, 185], textColor: [255, 255, 255] } },
      { content: formatCurrency(totals.bilty), styles: { fontStyle: 'bold', fillColor: [41, 128, 185], textColor: [255, 255, 255] } },
      { content: formatCurrency(totals.received), styles: { fontStyle: 'bold', fillColor: [41, 128, 185], textColor: [255, 255, 255] } },
      { content: formatCurrency(totals.pending), styles: { fontStyle: 'bold', fillColor: [41, 128, 185], textColor: [255, 193, 193] } }
    ]);

    autoTable(doc, {
      startY: currentY,
      head,
      body,
      styles: {
        fontSize: 8,
        cellPadding: 5,
        lineColor: [200, 200, 200],
        lineWidth: 0.5
      },
      headStyles: {
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: 'center'
      },
      bodyStyles: {
        textColor: [50, 50, 50]
      },
      alternateRowStyles: {
        fillColor: [248, 249, 250]
      },
      columnStyles: {
        6: { halign: 'right' },
        7: { halign: 'right' },
        8: { halign: 'right', textColor: [220, 53, 69], fontStyle: 'bold' }
      },
      theme: 'grid',
      margin: { left: 40, right: 40 },
    });
  }

  // Add final page number
  addPageNumber(pageNum, pageNum);

  const filename = `${COMPANY_NAME.replace(/\s+/g, "_")}_Receivable_Report_${exportType === 'party' ? 'Party_Wise' : 'Bilty_Wise'}.pdf`;
  doc.save(filename);
};