// src/components/ablsoftware/Maintance/common/NonReceivablePdf.ts

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const COMPANY_NAME = "AL NASAR BASHEER LOGISTICS";
const REPORT_TITLE = "Non-Receivable Orders Report";

export interface NonReceivableRow {
  serial?: number | string;
  orderNo: string;
  orderDate?: string;
  vehicleNo?: string;
  vendor?: string;
  departure?: string;
  destination?: string;
  vehicleMunshyana?: string;
}

export interface NonReceivablePdfParams {
  rows: NonReceivableRow[];
  startDate?: string;
  endDate?: string;
}

const formatDisplayDate = (d?: string) => {
  if (!d) return "-";
  try {
    const dt = new Date(d);
    if (Number.isNaN(dt.getTime())) return d;
    const dd = String(dt.getDate()).padStart(2, "0");
    const mm = String(dt.getMonth() + 1).padStart(2, "0");
    const yyyy = dt.getFullYear();
    return `${dd}-${mm}-${yyyy}`;
  } catch {
    return d;
  }
};

export const exportNonReceivableToPDF = ({
  rows,
  startDate,
  endDate,
}: NonReceivablePdfParams) => {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "A4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  let headerShown = false;

  const addCompanyHeader = () => {
    doc.setFillColor(220, 53, 69); // Red for non-receivable
    doc.rect(0, 0, pageWidth, 55, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(19);
    doc.setTextColor(255, 255, 255);
    doc.text(COMPANY_NAME, pageWidth / 2, 32, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(240, 240, 240);
    doc.text("Transport & Logistics Solutions", pageWidth / 2, 48, { align: "center" });
  };

  const addReportTitleAndDate = () => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(220, 53, 69);
    doc.text(REPORT_TITLE, pageWidth / 2, 80, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);

    doc.text(
      `From: ${startDate ? formatDisplayDate(startDate) : "All Dates"}`,
      40,
      100,
      { align: "left" }
    );
    doc.text(
      `To: ${endDate ? formatDisplayDate(endDate) : "All Dates"}`,
      pageWidth / 2,
      100,
      { align: "center" }
    );
    doc.text(
      `Generated: ${formatDisplayDate(new Date().toISOString())} at ${new Date().toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      })}`,
      pageWidth - 40,
      100,
      { align: "right" }
    );

    doc.setDrawColor(220, 53, 69);
    doc.setLineWidth(1.2);
    doc.line(40, 110, pageWidth - 40, 110);
  };

  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(
      `Generated by ZMS - Al Nasar Basheer Logistics Management System`,
      40,
      doc.internal.pageSize.height - 18
    );
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth - 40,
      doc.internal.pageSize.height - 18,
      { align: "right" }
    );
  };

  // Add header
  addCompanyHeader();
  addReportTitleAndDate();

  const head = [
    [
      "SNo",
      "Order No",
      "Order Date",
      "Vehicle No",
      "Vendor",
      "Departure",
      "Destination",
      "Vehicle Munshyana",
    ],
  ];

  const body = rows.map((r, idx) => [
    String(idx + 1),
    r.orderNo || "-",
    formatDisplayDate(r.orderDate),
    r.vehicleNo || "-",
    r.vendor || "-",
    r.departure || "-",
    r.destination || "-",
    r.vehicleMunshyana || "-",
  ]);

  // Add note about non-receivable orders
  const noteStartY = 115;
  doc.setFontSize(9);
  doc.setTextColor(220, 53, 69);
  doc.setFont("helvetica", "bold");
//   doc.text(
//     `⚠ Note: These are orders without any consignments/bilties added.`,
//     40,
//     noteStartY
//   );

  autoTable(doc, {
    startY: noteStartY + 15,
    head,
    body,
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 6, lineWidth: 0.4, lineColor: [180, 180, 180] },
    headStyles: {
      fillColor: [220, 53, 69],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "center",
    },
    columnStyles: {
      0: { cellWidth: 60, halign: "center" },
      1: { cellWidth: 90 },
      2: { cellWidth: 80, halign: "center" },
      3: { cellWidth: 80 },
      4: { cellWidth: 120 },
      5: { cellWidth: 90 },
      6: { cellWidth: 90 },
      7: { cellWidth: 130 },
    },
    margin: { left: 50, right: 50 },
    didDrawPage: (data) => {
      if (data.pageNumber > 1) {
        // Re-add header on new pages
        addCompanyHeader();
        addReportTitleAndDate();
        doc.setFontSize(9);
        doc.setTextColor(220, 53, 69);
        doc.setFont("helvetica", "bold");
        // doc.text(
        //   `⚠ Note: These are orders without any consignments/bilties added.`,
        //   40,
        //   noteStartY
        // );
      }
      addFooter(data.pageNumber, doc.internal.pages.length - 1);
    },
  });

  const filename = `Non_Receivable_Orders_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
};
